config/routes.rb
Rails.application.routes.draw do
  get 'home/my'
  get 'home/refresh_playlist'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :musics
  resources :user_musics
  resources :groups
  resources :group_musics
  resources :likes
  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups

  has_many :group_musics, dependent: :destroy

  def image_url
    self.image.url.present? ? self.image.url : '/ringle.jpeg'
  end
end

app/models/group_music.rb
class GroupMusic < ApplicationRecord
  belongs_to :group
  belongs_to :music, optional: true
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :music

  after_save :add_music_love
  after_destroy :destroy_music_love

  private

  def add_music_love
    self.music.increment!(:like_count)
  end

  def destroy_music_love
    music = self.music
    if music.like_count >= 1
      music.decrement!(:like_count)
    end
  end
end

app/models/music.rb
class Music < ApplicationRecord
  has_many :user_musics, dependent: :nullify
  has_many :likes, dependent: :nullify
  has_many :group_musics, dependent: :nullify

  include PgSearch::Model
  pg_search_scope :music_search,
    against: {
      title: 'A',
      album_name: 'B',
      artist_name: 'C'
    },
    using: {
      tsearch: { prefix: true, dictionary: 'simple', tsvector_column: 'searchable' }
    }
  # scope :force_index, ->(index) { from("#{table_name} FORCE INDEX(#{index})") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_musics, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups

  has_many :group_musics, dependent: :destroy

  def has_music_love?(music)
    self.likes.find_by(music: music).present?
  end

  def has_group?
    self&.groups&.any?
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_music.rb
class UserMusic < ApplicationRecord
  belongs_to :user
  belongs_to :music, optional: true

  after_save :check_record_count

  private

  def check_record_count
    playlist_records = self.user.user_musics
    if playlist_records.count > 100
      playlist_records.limit(playlist_records.count - 100).order(:created_at).destroy_all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :add_playlists
  before_action :configure_permitted_parameters, if: :devise_controller?

  def add_playlists(music_ids, group_id)
    group = Group.find group_id
    # n개 추가
    if music_ids.length > 1
      AddGroupPlaylistRecordsJob.perform_async(music_ids, current_user.email, group.id)
    # 1개 추가
    else
      music = Music.find music_ids.join(",")
      GroupMusic.create(group: group, music: music, user: current_user)
      CheckGroupPlaylistRecordsJob.perform_async(group.id)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password]
    devise_parameter_sanitizer.permit :account_update, keys: [:email, :password, :password_confirmation]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_musics, except: [:show]
  before_action :load_object, only: [:show, :destroy]

  def index
    @groups = current_user&.groups
  end

  def new ;end

  def show ;end

  def create
    @group = Group.create(group_params)
    UserGroup.create(user: current_user, group: @group)
    music_ids = @music_ids.split(" ")
    if music_ids.any?
      add_playlists(music_ids, @group.id)
    end
  end

  def destroy
    @group.destroy
  end

  private

  def group_params
    params.require(:group).permit(:title, :intro, :image)
  end

  def find_musics
    @music_ids = params[:music_ids]
  end

  def load_object
    @group = Group.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index ;end

  def my
    @love_musics = current_user.likes.order(created_at: :desc)
    @playlists = current_user.user_musics.order(created_at: :desc)
    @groups = current_user.groups
  end

  def refresh_playlist
    @playlists = current_user.user_musics.order(created_at: :desc)
    @sort_condition = "playlist"
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :find_sort_condition

  def create
    @music = Music.find params[:music]
    current_user.likes.create(music: @music)
  end

  def destroy
    @music = Music.find params[:id]
    current_user.likes.find_by(music: @music).destroy
  end

  private

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def find_sort_condition
    @sort_condition = params[:sort_condition]
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
    @keyword = params[:music_search]
    @musics = Music.music_search(@keyword)
    @popular_musics = @musics.reorder(like_count: :desc)
    @new_musics = @musics.reorder(created_at: :desc)
  end
end

app/controllers/user_musics_controller.rb
class UserMusicsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_musics, only: [:create, :destroy]

  def index
    @user_musics = current_user.user_musics.order(created_at: :desc)
  end

  # 재생목록 추가
  def create
    @sort_condition = params[:sort_condition]
    @music_ids.each do |music_id|
      music = Music.find music_id
      current_user.user_musics.create(music: music)
    end
  end

  # 재생목록 삭제
  def destroy
    @music_ids.each do |music_id|
      music = Music.find music_id
      current_user.user_musics.where(music: music).order(created_at: :desc).destroy_all
    end
  end

  private

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def find_musics
    @music_ids = params[:music_ids]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_musics_helper.rb
module GroupMusicsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/user_musics_helper.rb
module UserMusicsHelper
end

app/views/home/_group_playlist.html.erb
<% if groups.any? %>
  <% groups.each do |group| %>
    <div class="row py-3">
      <div class="col-3 text-center">
        <%= link_to group_path(group), target: "_blank" do %>
          <%= image_tag group.image_url, class: "clickable square-image" %>
        <% end %>
      </div>
      <div class="col-6 text-start">
        <%= link_to group_path(group), class: "no-line ringle-color", target: "_blank" do %>
          <h5 class="clickable"><%= group.title %></h5>
        <% end %>
        <small><%= group.intro %></small><br/>
        <small style="position: relative; bottom: 0%;"><span class="ringle-color"><%= group.group_musics.count %>곡</span><span class="text-gray-color">&nbsp;|&nbsp;</span><%= group.created_at.strftime("%y.%m.%d") %></small>
      </div>
      <div class="col-3 vertical-center">
        <div class="btn ringle-button text-white" onclick="remove_group(<%= group.id %>)">
          <i class="fas fa-times"></i>&nbsp;&nbsp;삭제
        </div>
      </div>
    </div>
    <hr class="mt-0">
  <% end %>
<% else %>
  <p class="mt-4 text-center">그룹이 없습니다.</p>
  <div class="text-center">
    <%= link_to "그룹 만들기", new_group_path, class: "no-line text-white btn ringle-button", target: "_blank" %>
  </div>
<% end %>

<script>
  function remove_group(group_id) {
    $.ajax({
      url: '/groups/' + group_id,
      type: 'DELETE'
    });
  }
</script>

app/views/home/_list.html.erb
<%= render 'shared/music_controller', sort_condition: sort_condition %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col">곡명</th>
      <th scope="col">아티스트명</th>
      <th scope="col">앨범명</th>
      <th scope="col">추가 날짜</th>
    </tr>
  </thead>
  <tbody>
    <% if user_musics.any? %>
      <% user_musics.includes(:music).each do |user_music| %>
        <% music = user_music.music %>
        <tr>
          <th scope="row"></th>
          <td><input class="<%= sort_condition %>_check_music" type="checkbox" value=<%= music.id %>></td>
          <% cache(music) do %>
            <td><%= music.title %></td>
            <td class="ringle-color"><strong><%= music.artist_name %></strong></td>
            <td><%= music.album_name %></td>
            <td><%= user_music.created_at.strftime('%y.%m.%d') %></td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <th scope="row"></th>
        <td>곡이 없습니다.</td>
        <td></td><td></td><td></td><td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  <%= render 'shared/select_all_checkbox', sort_condition: sort_condition %>
  <%= render 'shared/add_playlists', sort_condition: sort_condition %>
  <%= render 'shared/remove_playlists', sort_condition: sort_condition %>
</script>

app/views/home/index.html.erb
<style>
  .img-container {
    margin-top: 8%;
  }
  .input-height {
    height: 50px;
  }
</style>

<%= render 'shared/header' %>
<div class="container">
  <div class="img-container text-center">
    <%= link_to root_path do %>
      <%= image_tag '/ringle.jpeg' %>
    <% end %>
  </div>
  <div class="search-container mt-5">
    <%= form_tag('/musics', method: :get, class: "form-inline row mx-3") do %>
      <div class="col-2"></div>
      <div class="col-8 d-flex align-items-center flex-nowrap">
        <%= text_field_tag :music_search, "", class: "form-control input-height no-border-radius search-field", placeholder: "곡명, 가수명, 앨범명을 입력하세요." %>
        <button class="btn btn-primary input-height no-border-radius" type="submit"><i class="fas fa-search"></i></button>
      </div>
      <div class="col-2"></div>
    <% end %>
  </div>
</div>

app/views/home/my.html.erb
<style>
  .square-image {
    width: 80px; height: 80px;
  }
</style>

<div class="container mt-5">
  <%= render 'shared/back' %>
  <h3 class="text-center my-4">마이뮤직</h3>
  <%= link_to '로그아웃', destroy_user_session_path, method: :DELETE %> <br>
  <%= link_to '홈으로 가기', root_path, class: "no-line ringle-color" %>
  <ul class="nav nav-tabs mt-5 justify-content-center" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active ringle-color" id="love-music-tab" data-bs-toggle="tab" data-bs-target="#love_music" type="button" role="tab" aria-selected="true">좋아요 한 곡</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link ringle-color" id="playlist-tab" data-bs-toggle="tab" data-bs-target="#playlist" type="button" role="tab" aria-selected="false">재생목록</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link ringle-color" id="group-playlist-tab" data-bs-toggle="tab" data-bs-target="#group-playlist" type="button" role="tab" aria-selected="false">그룹재생목록</button>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade show active" id="love_music" role="tabpanel" aria-labelledby="love-music-tab">
      <%= render 'home/list', user_musics: @love_musics, sort_condition: 'love' %>
    </div>
    <div class="tab-pane fade" id="playlist" role="tabpanel" aria-labelledby="playlist-tab">
      <%= render 'home/list', user_musics: @playlists, sort_condition: 'playlist' %>
    </div>
    <div class="tab-pane fade" id="group-playlist" role="tabpanel" aria-labelledby="group-playlist-tab">
      <%= render 'home/group_playlist', groups: @groups, sort_condition: 'group-playlist' %>
    </div>
  </div>
</div>

<script>
  $('#playlist-tab').on('click', function() {
    $.ajax({
      url: '/home/refresh_playlist',
      type: 'GET'
    });
  });
</script>

app/views/home/refresh_playlist.js.erb
$("#playlist").html("<%= j(render('home/list', user_musics: @playlists, sort_condition: @sort_condition)) %>")