config/routes.rb
Rails.application.routes.draw do
  get 'home/my'
  get 'home/refresh_playlist'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :musics
  resources :user_musics
  resources :groups
  resources :group_musics
  resources :likes
  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups

  has_many :group_musics, dependent: :destroy

  def image_url
    self.image.url.present? ? self.image.url : '/ringle.jpeg'
  end
end

app/models/group_music.rb
class GroupMusic < ApplicationRecord
  belongs_to :group
  belongs_to :music, optional: true
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :music

  after_save :add_music_love
  after_destroy :destroy_music_love

  private

  def add_music_love
    self.music.increment!(:like_count)
  end

  def destroy_music_love
    music = self.music
    if music.like_count >= 1
      music.decrement!(:like_count)
    end
  end
end

app/models/music.rb
class Music < ApplicationRecord
  has_many :user_musics, dependent: :nullify
  has_many :likes, dependent: :nullify
  has_many :group_musics, dependent: :nullify

  include PgSearch::Model
  pg_search_scope :music_search,
    against: {
      title: 'A',
      album_name: 'B',
      artist_name: 'C'
    },
    using: {
      tsearch: { prefix: true, dictionary: 'simple', tsvector_column: 'searchable' }
    }
  # scope :force_index, ->(index) { from("#{table_name} FORCE INDEX(#{index})") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_musics, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups

  has_many :group_musics, dependent: :destroy

  def has_music_love?(music)
    self.likes.find_by(music: music).present?
  end

  def has_group?
    self&.groups&.any?
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_music.rb
class UserMusic < ApplicationRecord
  belongs_to :user
  belongs_to :music, optional: true

  after_save :check_record_count

  private

  def check_record_count
    playlist_records = self.user.user_musics
    if playlist_records.count > 100
      playlist_records.limit(playlist_records.count - 100).order(:created_at).destroy_all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :add_playlists
  before_action :configure_permitted_parameters, if: :devise_controller?

  def add_playlists(music_ids, group_id)
    group = Group.find group_id
    # n개 추가
    if music_ids.length > 1
      AddGroupPlaylistRecordsJob.perform_async(music_ids, current_user.email, group.id)
    # 1개 추가
    else
      music = Music.find music_ids.join(",")
      GroupMusic.create(group: group, music: music, user: current_user)
      CheckGroupPlaylistRecordsJob.perform_async(group.id)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password]
    devise_parameter_sanitizer.permit :account_update, keys: [:email, :password, :password_confirmation]
  end
end

app/controllers/group_musics_controller.rb
class GroupMusicsController < ApplicationController
  before_action :find_music_and_group

  def create
    add_playlists(@music_ids, @group_id)
  end

  def destroy
    @group = Group.find @group_id
    # n개 삭제
    if @music_ids.length > 1
      DestroyGroupPlaylistRecordsJob.perform_async(@music_ids, @group.id)
    # 1개 삭제
    else
      music = Music.find @music_ids.join(",")
      @group.group_musics.where(music: music).order(created_at: :desc).first.destroy
    end
  end

  private

  def find_music_and_group
    @music_ids = params[:music_ids]
    @group_id = params[:group_id]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_musics, except: [:show]
  before_action :load_object, only: [:show, :destroy]

  def index
    @groups = current_user&.groups
  end

  def new ;end

  def show ;end

  def create
    @group = Group.create(group_params)
    UserGroup.create(user: current_user, group: @group)
    music_ids = @music_ids.split(" ")
    if music_ids.any?
      add_playlists(music_ids, @group.id)
    end
  end

  def destroy
    @group.destroy
  end

  private

  def group_params
    params.require(:group).permit(:title, :intro, :image)
  end

  def find_musics
    @music_ids = params[:music_ids]
  end

  def load_object
    @group = Group.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index ;end

  def my
    @love_musics = current_user.likes.order(created_at: :desc)
    @playlists = current_user.user_musics.order(created_at: :desc)
    @groups = current_user.groups
  end

  def refresh_playlist
    @playlists = current_user.user_musics.order(created_at: :desc)
    @sort_condition = "playlist"
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :find_sort_condition

  def create
    @music = Music.find params[:music]
    current_user.likes.create(music: @music)
  end

  def destroy
    @music = Music.find params[:id]
    current_user.likes.find_by(music: @music).destroy
  end

  private

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def find_sort_condition
    @sort_condition = params[:sort_condition]
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
    @keyword = params[:music_search]
    @musics = Music.music_search(@keyword)
    @popular_musics = @musics.reorder(like_count: :desc)
    @new_musics = @musics.reorder(created_at: :desc)
  end
end

app/controllers/user_musics_controller.rb
class UserMusicsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_musics, only: [:create, :destroy]

  def index
    @user_musics = current_user.user_musics.order(created_at: :desc)
  end

  # 재생목록 추가
  def create
    @sort_condition = params[:sort_condition]
    @music_ids.each do |music_id|
      music = Music.find music_id
      current_user.user_musics.create(music: music)
    end
  end

  # 재생목록 삭제
  def destroy
    @music_ids.each do |music_id|
      music = Music.find music_id
      current_user.user_musics.where(music: music).order(created_at: :desc).destroy_all
    end
  end

  private

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def find_musics
    @music_ids = params[:music_ids]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_musics_helper.rb
module GroupMusicsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/user_musics_helper.rb
module UserMusicsHelper
end

app/views/group_musics/create.js.erb
Swal.fire({
  text: '그룹 플레이리스트에 추가되었습니다.',
  showCloseButton: true,
  allowOutsideClick: false,
  confirmButtonText: '<div class="text-white">플레이리스트 확인하기</div>'
}).then(function(res) {
  window.location.href = '<%= home_my_path %>';
});

app/views/groups/_group_playlist.html.erb
<% @group.group_musics.includes(:music, :user).order(created_at: :desc).each do |group_music| %>
  <% music = group_music.music %>
  <% user = group_music.user %>
  <div class="row mb-3">
    <div class="col-1 vertical-center text-center">
      <input class="general_check_music" type="checkbox" value="<%= music.id %>">
    </div>
    <div class="col-3 vertical-center">
      <%= image_tag '/ringle.jpeg', style: "width: 50%;" %>
    </div>
    <div class="col-5 vertical-center">
      <h4 class="mb-0"><%= music.title %></h4>
      <small><%= music.artist_name %></small>
    </div>
    <div class="col-3 vertical-center">
      <%= user.email %>
    </div>
  </div>
  <hr>
<% end %>

app/views/groups/create.js.erb
Swal.fire({
  text: '그룹이 추가되었습니다.',
  allowOutsideClick: false,
  confirmButtonText: '<a class="no-line text-white" href="<%= home_my_path %>">그룹 확인하기</a>',
})

app/views/groups/index.js.erb
<% if current_user&.has_group? %>
  Swal.fire({
    title: '<h5>그룹 플레이리스트 담기</h5>',
    html:
      '<% @groups.each do |group| %>' +
        '<div class="row">' +
          '<div class="col-3">' +
            '<%= image_tag group.image_url, style: "width: 80px; height: 80px;" %>' +
          '</div>' +
          '<div class="col-6 text-start">' +
            '<h5><%= group.title %></h5>' +
            '<small><%= group.intro %></small><br/>' +
            '<small style="position: relative; bottom: 0%;"><%= group.group_musics.count %>곡 | <%= group.created_at.strftime("%y.%m.%d") %></small>' +
          '</div>' +
          '<div class="col-3 vertical-center">' +
            '<div class="btn btn-info text-white" onclick="add_group_playlist(<%= @music_ids %>, <%= group.id %>)">' +
              '선택' +
            '</div>' +
          '</div>' +
        '</div>' +
        '<hr/>' +
      '<% end %>',
    confirmButtonText: '<a class="no-line text-white" href="<%= new_group_path(music_ids: @music_ids) %>" target="_blank">그룹 만들기</a>'
  })
<% else %>
  Swal.fire({
    text: '소속된 그룹이 없습니다.',
    confirmButtonText: '<a class="no-line text-white" href="<%= new_group_path(music_ids: @music_ids) %>" target="_blank">그룹 만들기</a>',
  })
<% end %>

function add_group_playlist(music_ids, group_id) {
  $.ajax({
    url: '/group_musics',
    type: 'POST',
    data: {
      music_ids: music_ids,
      group_id: group_id
    }
  });
}

app/views/groups/new.html.erb
<div class="container mt-5">
  <%= render 'shared/back' %>
  <h3 class="text-center my-4">그룹 만들기</h3>
  <%= form_for Group.new, remote: true do |f| %>
    <%= hidden_field_tag 'music_ids', @music_ids %>
    <div class="my-4">
      <label for="InputTitle" class="form-label">제목</label>
      <%= f.text_field :title, class: "form-control", id: "InputTitle" %>
    </div>
    <div class="mb-4">
      <label for="InputImage" class="form-label">그룹 이미지</label>
      <%= f.file_field :image, class: "form-control", id: "InputImage" %>
    </div>
    <div class="mb-4">
      <label for="InputIntro" class="form-label">소개글</label>
      <%= f.text_area :intro, rows: 2, cols: 1, class: "form-control", id: "InputIntro" %>
    </div>
    <%= f.submit "생성", class: "ringle-button text-white py-2 d-grid gap-2 col-2 mx-auto no-border"  %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="container mt-5">
  <h3 class="text-center my-4">그룹 재생목록</h3>
  <div class="toolbar mt-3 mb-4">
    <div class="btn ringle-button text-white" onclick="check_all('general')">전체선택</div>
    <div class="btn ringle-button text-white" onclick="remove_playlists('general')">
      <i class="fas fa-times"></i>&nbsp;&nbsp;삭제
    </div>
  </div>
  <div class="container scrollable">
    <%= render 'groups/group_playlist' %>
  </div>
</div>

<script>
  <%= render 'shared/select_all_checkbox', sort_condition: 'general' %>
  function remove_playlists(sort_condition) {
    <%= render 'shared/check_musics', sort_condition: 'general' %>
    if(checks.is(":checked")) {
      $.ajax({
        url: '/group_musics/destroy',
        type: 'DELETE',
        data: {
          music_ids: check_array,
          group_id: <%= @group.id %>
        }
      });
    }
  }
</script>

app/views/likes/create.js.erb
$('#<%= @sort_condition %>_music_love_<%= @music.id %>').html("<%= j(render('musics/music_love', music: @music, sort_condition: @sort_condition)) %>")

app/views/likes/destroy.js.erb
$('#<%= @sort_condition %>_music_love_<%= @music.id %>').html("<%= j(render('musics/music_love', music: @music, sort_condition: @sort_condition)) %>")

app/views/musics/_music_love.html.erb
<% if current_user&.has_music_love?(music) %>
  <i class="fas fa-heart clickable" onclick="music_love_delete(<%= music.id %>, '<%= sort_condition %>')" style="color: red;"></i>
<% else %>
  <i class="far fa-heart clickable" onclick="music_love(<%= music.id %>, '<%= sort_condition %>')"></i>
<% end %>
&nbsp;<%= music.likes.count %>

<script>
  function music_love(music, sort_condition) {
    $.ajax({
      url: '/likes/',
      type: 'POST',
      data: {
        music: music,
        sort_condition: sort_condition
      }
    });
  }

  function music_love_delete(music, sort_condition) {
    $.ajax({
      url: '/likes/' + music,
      type: 'DELETE',
      data: {
        sort_condition: sort_condition
      }
    });
  }
</script>

app/views/musics/_result.html.erb
<%= render 'shared/music_controller', sort_condition: sort_condition %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col">곡명</th>
      <th scope="col">아티스트명</th>
      <th scope="col">앨범명</th>
      <th scope="col">좋아요</th>
    </tr>
  </thead>
  <tbody>
    <% if musics.any? %>
      <% musics.each do |music| %>
        <tr>
          <th scope="row"></th>
          <td><input class="<%= sort_condition %>_check_music" type="checkbox" value=<%= music.id %>></td>
          <% cache(music) do %>
            <td><%= music.title %></td>
            <td class="ringle-color"><strong><%= music.artist_name %></strong></td>
            <td><%= music.album_name %></td>
          <% end %>
          <td id="<%= sort_condition %>_music_love_<%= music.id %>">
            <%= render 'music_love', music: music, sort_condition: sort_condition %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <th scope="row"></th>
        <td>찾으시는 결과가 존재하지 않습니다.</td>
        <td></td><td></td><td></td><td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  <%= render 'shared/select_all_checkbox', sort_condition: sort_condition %>
  <%= render 'shared/add_playlists', sort_condition: sort_condition %>
</script>

app/views/musics/index.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="search-container mt-5">
    <%= form_tag('/musics', method: :get, class: "form-inline row mr-3") do %>
      <div class="col-2 text-center">
        <%= link_to root_path do %>
          <%= image_tag '/ringle.jpeg', style: "width: 60%;" %>
        <% end %>
      </div>
      <div class="col-5 d-flex align-items-center flex-nowrap">
        <%= text_field_tag :music_search, "", class: "form-control no-border-radius search-field" %>
        <button class="btn btn-primary no-border-radius" type="submit"><i class="fas fa-search"></i></button>
      </div>
      <div class="col-2"></div>
    <% end %>
  </div>
  <ul class="nav nav-tabs mt-5" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active ringle-color" id="accuracy-tab" data-bs-toggle="tab" data-bs-target="#accuracy" type="button" role="tab" aria-selected="true">정확도순</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link ringle-color" id="popular-tab" data-bs-toggle="tab" data-bs-target="#popular" type="button" role="tab" aria-selected="false">인기순</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link ringle-color" id="new-tab" data-bs-toggle="tab" data-bs-target="#new" type="button" role="tab" aria-selected="false">최신순</button>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade show active" id="accuracy" role="tabpanel" aria-labelledby="accuracy-tab">
      <%= render 'musics/result', musics: @musics, sort_condition: 'accuracy' %>
    </div>
    <div class="tab-pane fade" id="popular" role="tabpanel" aria-labelledby="popular-tab">
      <%= render 'musics/result', musics: @popular_musics, sort_condition: 'popular' %>
    </div>
    <div class="tab-pane fade" id="new" role="tabpanel" aria-labelledby="new-tab">
      <%= render 'musics/result', musics: @new_musics, sort_condition: 'new' %>
    </div>
  </div>
</div>

app/views/user_musics/_playlist.html.erb
<% @user_musics.includes(:music).each do |user_music| %>
  <% music = user_music.music %>
  <div class="row mb-3">
    <div class="col-1 vertical-center text-center">
      <input class="general_check_music" type="checkbox" value="<%= music.id %>">
    </div>
    <div class="col-3 vertical-center">
      <%= image_tag '/ringle.jpeg', style: "width: 50%;" %>
    </div>
    <div class="col-5 vertical-center">
      <h4 class="mb-0"><%= music.title %></h4>
      <small><%= music.artist_name %></small>
    </div>
  </div>
  <hr>
<% end %>

app/views/user_musics/create.js.erb
Swal.fire({
  text: '재생목록에 추가되었습니다.',
  showCloseButton: true,
  allowOutsideClick: false,
  confirmButtonText: '<a class="no-line text-white" href="<%= user_musics_path %>" target="_blank">재생목록 확인하기</a>',
}).then(function(res) {
  $(".<%= @sort_condition %>_check_music").prop('checked', false);
});

app/views/user_musics/destroy.js.erb
Swal.fire({
  text: '삭제되었습니다.',
  confirmButtonText: '확인',
}).then(function(res) {
  setTimeout(function() {
    location.reload();
  }, 500);
});

app/views/user_musics/index.html.erb
<div class="container mt-5">
  <h3 class="text-center my-4">재생목록</h3>
  <div class="toolbar mt-3 mb-4">
    <div class="btn ringle-button text-white" onclick="check_all('general')">전체선택</div>
    <div class="btn ringle-button text-white" onclick="remove_playlists('general')">
      <i class="fas fa-times"></i>&nbsp;&nbsp;삭제
    </div>
  </div>
  <div class="container scrollable">
    <%= render 'user_musics/playlist' %>
  </div>
</div>

<script>
  <%= render 'shared/select_all_checkbox', sort_condition: 'general' %>
  <%= render 'shared/remove_playlists', sort_condition: 'general' %>
</script>